# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [28]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [29]:
### [your code here]
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/build-en

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [30]:
### [your code here]
a = np.random.random((2,3,5))


### 4. Print a.


In [31]:
### [your code here]
print(a)

[[[0.47621505 0.75247101 0.9424672  0.41496121 0.91340793]
  [0.80955922 0.79744867 0.82034741 0.17483264 0.4053327 ]
  [0.79828208 0.08715235 0.7281361  0.76441957 0.11418006]]

 [[0.64368723 0.6154793  0.67567042 0.58012846 0.44763398]
  [0.62934778 0.26022463 0.93181988 0.40678778 0.26811261]
  [0.04376389 0.56083097 0.60393801 0.17899567 0.21490856]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [32]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [33]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [34]:
### [your code here]
print(a.shape == b.shape)


False



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
print(a +b)
#no because the shapes of a and b are not compatible for broadcasting. The shape of a is (2, 3, 5) and the shape of b is (5, 2, 3). In order for two arrays to be broadcastable, their shapes must be compatible according to the broadcasting rules. In this case, the dimensions do not align properly for broadcasting, so the addition operation cannot be performed.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [36]:
### [your code here]
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [37]:
### [your code here]
d = a + c
print(d)
# they have the same shape now, so the addition operation can be performed successfully. The resulting array d will have the same shape as a and b, which is (2, 3, 5).


[[[1.47621505 1.75247101 1.9424672  1.41496121 1.91340793]
  [1.80955922 1.79744867 1.82034741 1.17483264 1.4053327 ]
  [1.79828208 1.08715235 1.7281361  1.76441957 1.11418006]]

 [[1.64368723 1.6154793  1.67567042 1.58012846 1.44763398]
  [1.62934778 1.26022463 1.93181988 1.40678778 1.26811261]
  [1.04376389 1.56083097 1.60393801 1.17899567 1.21490856]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [38]:
### [your code here]
print(a,d)
# d is the result of adding arrays a and b together. Since both arrays have the same shape (2, 3, 5), the addition operation can be performed element-wise. The resulting array d will also have the shape (2, 3, 5) and will contain the sum of corresponding elements from a and b.

[[[0.47621505 0.75247101 0.9424672  0.41496121 0.91340793]
  [0.80955922 0.79744867 0.82034741 0.17483264 0.4053327 ]
  [0.79828208 0.08715235 0.7281361  0.76441957 0.11418006]]

 [[0.64368723 0.6154793  0.67567042 0.58012846 0.44763398]
  [0.62934778 0.26022463 0.93181988 0.40678778 0.26811261]
  [0.04376389 0.56083097 0.60393801 0.17899567 0.21490856]]] [[[1.47621505 1.75247101 1.9424672  1.41496121 1.91340793]
  [1.80955922 1.79744867 1.82034741 1.17483264 1.4053327 ]
  [1.79828208 1.08715235 1.7281361  1.76441957 1.11418006]]

 [[1.64368723 1.6154793  1.67567042 1.58012846 1.44763398]
  [1.62934778 1.26022463 1.93181988 1.40678778 1.26811261]
  [1.04376389 1.56083097 1.60393801 1.17899567 1.21490856]]]



### 12. Multiply a and c. Assign the result to e.


In [39]:
### [your code here]
e = a * c




### 13. Does e equal to a? Why or why not?


In [40]:
### [your code here]
print(a == c)



[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [42]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(type(d_max), type(d_min), type(d_mean))


<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [43]:
### [your code here]
f = np.empty((2,3,5))






### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [46]:
### [your code here]
print(f)

[1.47621505 1.41496121 1.17483264 1.4053327  1.08715235 1.11418006
 1.44763398 1.26022463 1.40678778 1.26811261 1.17899567 1.21490856]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [47]:
### [your code here]
labels = np.empty(d.shape, dtype="U1")
labels[d == d_min] = "A"
labels[(d > d_min) & (d < d_mean)] = "B"
labels[d == d_mean] = "C"
labels[(d > d_mean) & (d < d_max)] = "D"
labels[d == d_max] = "E"
print(labels)

[[['B' 'D' 'E' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'B']]

 [['D' 'D' 'D' 'D' 'B']
  ['D' 'B' 'D' 'B' 'B']
  ['A' 'D' 'D' 'B' 'B']]]
